### ISSUE TITLE
App crashing when enabling cloud sync

### ISSUE THREAD

**Issue by bahuma20** [JohnSimonCo/PayBack#1]
Hi,

i've fresh istalled the app on my OnePlus One with Cyanogen OS 12.1 based on Android 5.1.1

When i'm trying to enable cloud sync, it prompts me to sign in using my google account. I select the account and the app crashes.

![screenshot_2015-09-04-09-13-59](https://cloud.githubusercontent.com/assets/5746121/9678450/a3db5fb6-52e5-11e5-8024-06ba133ce007.png)
![screenshot_2015-09-04-09-14-03](https://cloud.githubusercontent.com/assets/5746121/9678457/b1ae2c90-52e5-11e5-9bf2-59c8ee684683.png)
![screenshot_2015-09-04-09-14-07](https://cloud.githubusercontent.com/assets/5746121/9678459/b4262cca-52e5-11e5-8614-15b2535983a9.png)
![screenshot_2015-09-04-09-14-11](https://cloud.githubusercontent.com/assets/5746121/9678460/b6cd3e82-52e5-11e5-9249-562e5e555440.png)

**Comment by SweSnow** [comment]
Hi!

Can you try joining the beta for the new version of Pay Back <a href="https://play.google.com/apps/testing/com.johnsimon.payback">here</a> and report back as to whether or not the problems persist? We've had previous reports of this same issue but have been unable to preproduce it on our own.

**Comment by bahuma20** [comment]
Installed the 1.3 Beta 3 and it works. When is this release planned to be public available?

**Comment by SweSnow** [comment]
Great, we plan on releasing 1.3 in the coming days. All features have been finalized but we just want to make sure the new version is stable first.
